### ISSUE TITLE
Might need to handle wanted_id_properties ?

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/reconciliation#13]
This query returns more IDs than just dcid:

```
curl -X POST https://autopush.recon.datacommons.org/entity/resolve -d '{"wanted_id_properties":"dcid","entities":{"source_id":"newId/SantaClaraCountyId","entity_ids":{"ids":{"prop":"geoId","val":"06085"}}}}'
```

**Comment by Spaceenter** [comment]
This can be achieved by the simplified ID-based recon endpoint:

curl -X POST https://autopush.recon.datacommons.org/id/resolve -d '{"in_prop":"wikidataId","out_prop":"dcid","ids":["Q110739","Q30"]}'
